server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trackers
    username: postgres
    password: login456456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true